[package]
name = "vml"
version = "0.1.0"
authors = ["Mikhail Gordeev <obirvalger@altlinux.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = { version = "4.0.9", features = ["serde"] }
clap = "3.0.0-beta.2"
json = "0.12.4"
procfs = "0.9.1"
rand = "0.8.2"
serde = { version = "1.0.118", features = ["derive"] }
toml = "0.5.8"
walkdir = "2.3.1"
