[alt]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/alt-sisyphus-cloud-{{arch}}.qcow2"
description = "ALT Linux Sisyphus"
change = ["update-all", "delete"]

[alt-p10]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p10/cloud/alt-p10-cloud-{{arch}}.qcow2"
description = "ALT Linux p10"
change = ["update-all", "delete"]

[alt-p9]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p9/cloud/alt-p9-cloud-{{arch}}.qcow2"
description = "ALT Linux p9"
change = ["update-all", "delete"]

[alt-sisyphus]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/alt-sisyphus-cloud-{{arch}}.qcow2"
description = "ALT Linux Sisyphus"
change = ["update-all", "delete"]

[arch]
description = "Archlinux"
url = ""
get-url-prog = "vml-get-arch"
change = ["update-all", "delete"]

[ubuntu]
url = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-{{arch}}.img"
description = "latest Ubuntu release (22.04)"
change = ["update-all", "delete"]

[ubuntu.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-lts]
url = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-{{arch}}.img"
description = "latest LTS Ubuntu release (22.04)"
change = ["update-all", "delete"]

[ubuntu-lts.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-jammy]
url = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-{{arch}}.img"
description = "Ubuntu 22.04 Jammy Jellyfish"
change = ["update-all", "delete"]

[ubuntu-jammy.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-impish]
url = "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-{{arch}}.img"
description = "Ubuntu 21.10 Impish Indri"
change = ["update-all", "delete"]

[ubuntu-impish.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-hirsute]
url = "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-{{arch}}.img"
description = "Ubuntu 21.04 Hirsute Hippo"
change = ["update-all", "delete"]

[ubuntu-hirsute.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-focal]
url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-{{arch}}.img"
description = "Ubuntu 20.04 Focal Fossa"
change = ["update-all", "delete"]

[ubuntu-focal.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-bionic]
url = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-{{arch}}.img"
description = "Ubuntu 18.04 Bionic Beaver"
change = ["update-all", "delete"]

[ubuntu-bionic.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian]
url = "https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-{{arch}}.qcow2"
description = "Debian stable"
change = ["update-all", "delete"]

[debian.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-11]
url = "https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-{{arch}}.qcow2"
description = "Debian bullseye (stable)"
change = ["update-all", "delete"]

[debian-11.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-10]
url = "https://cloud.debian.org/images/cloud/buster/latest/debian-10-genericcloud-{{arch}}.qcow2"
description = "Debian buster (oldstable)"
change = ["update-all", "delete"]

[debian-10.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-9]
url = "https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-{{arch}}.qcow2"
description = "Debian stretch (oldoldstable)"
change = ["update-all", "delete"]

[debian-9.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[centos]
url = "https://cloud.centos.org/centos/8-stream/{{arch}}/images/CentOS-Stream-GenericCloud-8-20210603.0.{{arch}}.qcow2"
description = "CentOS stream"
change = ["update-all", "delete"]

[centos-stream]
url = "https://cloud.centos.org/centos/8-stream/{{arch}}/images/CentOS-Stream-GenericCloud-8-20210603.0.{{arch}}.qcow2"
description = "CentOS stream"
change = ["update-all", "delete"]

[centos-8]
url = "https://cloud.centos.org/centos/8/{{arch}}/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.{{arch}}.qcow2"
description = "CentOS 8"
change = ["update-all", "delete"]

[centos-7]
url = "https://cloud.centos.org/centos/7/images/CentOS-7-{{arch}}-GenericCloud.qcow2"
description = "CentOS 7"
change = ["update-all", "delete"]

[centos-6]
url = "https://cloud.centos.org/centos/6/images/CentOS-6-{{arch}}-GenericCloud.qcow2"
description = "CentOS 6"
change = ["update-all", "delete"]

[fedora]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/{{arch}}/images/Fedora-Cloud-Base-36-1.5.{{arch}}.qcow2"
description = "latest Fedora release (36)"
change = ["update-all", "delete"]

[fedora-rawhide]
url = ""
get-url-prog = "vml-get-fedora-rawhide"
description = "Fedora Rawhide"
change = ["update-all", "delete"]

[fedora-36]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/{{arch}}/images/Fedora-Cloud-Base-36-1.5.{{arch}}.qcow2"
description = "Fedora 36"
change = ["update-all", "delete"]

[fedora-35]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/{{arch}}/images/Fedora-Cloud-Base-35-1.2.{{arch}}.qcow2"
description = "Fedora 35"
change = ["update-all", "delete"]

[fedora-34]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/34/Cloud/{{arch}}/images/Fedora-Cloud-Base-34-1.2.{{arch}}.qcow2"
description = "Fedora 34"
change = ["update-all", "delete"]

[fedora-33]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/{{arch}}/images/Fedora-Cloud-Base-33-1.2.{{arch}}.qcow2"
description = "Fedora 33"
change = ["update-all", "delete"]

[opensuse]
url = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.{{arch}}-OpenStack-Cloud.qcow2"
description = "openSUSE Tumbleweed"
change = ["update-all", "delete"]

[opensuse-leap]
url = "https://download.opensuse.org/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.{{arch}}-OpenStack-Cloud.qcow2"
description = "openSUSE Leap 15.4"
change = ["update-all", "delete"]

[opensuse-tumbleweed]
url = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.{{arch}}-OpenStack-Cloud.qcow2"
description = "openSUSE Tumbleweed"
change = ["update-all", "delete"]
