[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Obirvalger/infer"]
git = "https://github.com/Obirvalger/infer"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
