[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/Obirvalger/faccess"]
git = "https://github.com/Obirvalger/faccess"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
