# NOTE user your own path
vms-dir = "~/vml"

nameservers = ["8.8.8.8"]

# treat vml-common.toml files in parent dirs as additional configs
config-hierarchy = true


[commands]
create.pull = true

# Do this when create vm that already exists: fail, ignore, replace
create.exists = "fail"

list.all = false

list.fold = true

remove.interactive = true

remove.verbose = true

start.wait-ssh = { on = true, attempts = 60, repeat = 2, sleep = 5, timeout = 1 }


[default]
memory = "2G"

display = "none"

nproc = 2

# ssh.authorized-keys = []

ssh.options = [
    "StrictHostKeyChecking=no",
    "UserKnownHostsFile=/dev/null",
    "LogLevel=ERROR",
]

ssh.port-user-network = "random"

ssh.port = 22

# Use 0.0.0.0 if you want to bind ssh port to all ip addresses
ssh.host-user-network = "127.0.0.1"

ssh.user = "root"

# Path to private key or "none" or "create"
ssh.key = "create"

cloud-init = true

# NOTE if not set create image from vm specifications
# cloud-init-image = "~/my-seed.img"

# net.type = "none"

# net.type = "tap"
# net.address = "192.168.0.2"
# net.tap = "tap0"
# net.gateway = "192.168.0.1"
# net.nameservers = ["8.8.8.8"]

net.type = "user"

minimum-disk-size = "30G"


[images]

default = "alt-sisyphus"

directory = "~/.local/share/vml/images"

# List of read only directories with images
other-directories-ro = []
