# NOTE user your own path
vms-dir = "~/vml"

list-fold = false


[default]
memory = "2G"

# display = "none"

nproc = 2

# ssh-options = ["StrictHostKeyChecking=no", "UserKnownHostsFile=/dev/null"]

# NOTE ssh-port-user must be specified to use ssh commands with user network
ssh-port-user-network = "random"

# NOTE ssh-port must be specified to use ssh commands with tap network
# ssh-port = 22

# ssh-user = "root"

# NOTE user your own path
# cloud-init-image = "~/my-seed.img"

user-network = true

minimum-disk-size = "30G"


[images]

default = "alt-sisyphus"

directory = "~/.local/share/vml/images"

# List of read only directories with images
other-directories-ro = []
