# NOTE user your own path
vms-dir = "~/vml"


[commands]
create.pull = true

# Do this when create vm that already exists: fail, ignore, replace
create.exists = "fail"

list.all = false

list.fold = true

start.cloud-init = true

start.wait-ssh-attempts = 60

start.wait-ssh-timeout = 1


[default]
memory = "2G"

display = "none"

nproc = 2

# ssh.authorized-keys = []

# ssh.options = [
    # "StrictHostKeyChecking=no",
    # "UserKnownHostsFile=/dev/null",
    # "LogLevel=ERROR",
# ]

ssh.port-user-network = "random"

ssh.port = 22

ssh.user = "root"

# Path to private key or "none" or "create"
ssh.key = "create"

# NOTE if not set create image from vm specifications
# cloud-init-image = "~/my-seed.img"

user-network = true

minimum-disk-size = "30G"


[images]

default = "alt-sisyphus"

directory = "~/.local/share/vml/images"

# List of read only directories with images
other-directories-ro = []
